---
name: 'CGI::FormBuilder::Mail::FormatMultiPart'
version: 1.000005
author:
  - 'Mark Hedges <hedges@ucsd.edu>'
abstract: 'Plugin module for CGI::FormBuilder->mailresults()'
license: perl
resources:
  license: 'http://dev.perl.org/licenses/'
requires:
  CGI::FormBuilder: '>= 3.0302'
  HTML::QuickTable: 0
  MIME::Lite: 0
  MIME::Types: 0
  Module::Build: 0
  Regexp::Common: 0
  Test::Exception: 0
  Test::More: 0
  Text::FormatTable: 0
  perl: '>= 5.6.0'
  version: 0.5
build_requires:
  CGI::FormBuilder: '>= 3.0302'
  HTML::QuickTable: 0
  MIME::Lite: 0
  MIME::Types: 0
  Module::Build: 0
  Regexp::Common: 0
  Test::Exception: 0
  Test::More: 0
  Text::FormatTable: 0
  perl: '>= 5.6.0'
  version: 0.5
provides:
  'CGI::FormBuilder::Mail::FormatMultiPart':
    file: lib/CGI/FormBuilder/Mail/FormatMultiPart.pm
    version: 1.000005
generated_by: 'Module::Build version 0.2801'
'meta-spec':
  url: 'http://module-build.sourceforge.net/META-spec-v1.2.html'
  version: 1.2
